export enum EntityType {
  GENERATOR = "GENERATOR",
  CAT = "CAT",
  HOT_AIR_BALLOON = "HOT_AIR_BALLOON",
  STAR = "STAR",
  SNAIL = "SNAIL",
  // GIANT_MARBLE = "GIANT_MARBLE",
  // FOX = "FOX",
  // DOG = "DOG",
  // ROBOT = "ROBOT",
  // FLOWER_LILY = "FLOWER_LILY",
  // FLOWER_ROSE = "FLOWER_ROSE",
  // VIRUS = "VIRUS",
  // DRONE = "DRONE",
}
